<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/favicon.ico" />
    <title>
        FrameX
    </title>

</head>

<body>
    <center>
        <script src="https://telegram.org/js/telegram-widget.js?7" <?= $nonce_code ?> data-telegram-login="<?= $botId ?>" data-size="large" data-auth-url="<?= $callbackUrl ?>" data-request-access="write">
        </script>
        <script>
            TWidgetLogin.auth();
        </script>
    </center>
</body>

</html>